remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

title: Utkarsh's Meditations
description: Welcome to my page! This page contains my meditations on various topics.
author: Utkarsh
minimal_mistakes_skin: "dark" # Options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
mermaid: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: 
        - wide
        - single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar: false
