remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - 
    scope:
      path: ""
    values:
      layout: single

title: Utkarsh's Meditations
description: Welcome to my page! This page contains my meditations on various topics.
author: Utkarsh

# Customize these as needed
minimal_mistakes_skin: "dark" # Options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
